# Generated by Django 5.0.6 on 2024-05-23 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaivariety",
            name="descriptions",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="chaivariety",
            name="date_added",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 23, 10, 47, 2, 23039, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
