# Generated by Django 5.0.6 on 2024-05-23 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chai", "0002_chaivariety_descriptions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaivariety",
            name="price",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="chaivariety",
            name="date_added",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 23, 11, 14, 55, 569128, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
