# Generated by Django 5.0.6 on 2024-06-02 11:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chai", "0003_chaivariety_price_alter_chaivariety_date_added"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="chaivariety",
            name="date_added",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 2, 11, 20, 21, 211250, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate_number", models.CharField(max_length=100)),
                (
                    "issued_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 6, 2, 11, 20, 21, 213250, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("valid_until", models.DateTimeField()),
                (
                    "chai",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="chai.chaivariety",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="chaiReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.TextField()),
                ("rating", models.IntegerField()),
                ("comment", models.TextField()),
                (
                    "date_added",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 6, 2, 11, 20, 21, 212250, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "chai",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chai.chaivariety",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                (
                    "chai_varieties",
                    models.ManyToManyField(
                        related_name="stores", to="chai.chaivariety"
                    ),
                ),
            ],
        ),
    ]
